# https://docs.microsoft.com/vsts/pipelines/languages/xamarin

jobs:
- job: Android
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    buildConfiguration: 'Release'
    outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  steps:
  - task: NuGetToolInstaller@0
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '**/*.sln'
  - task: XamarinAndroid@1
    displayName: 'Build Android'
    inputs:
      projectFile: '**/*droid*.csproj'
      outputDirectory: '$(outputDirectory)'
      configuration: '$(buildConfiguration)'
  - task: cake-build.cake.cake-build-task.Cake@0
    displayName: 'Run unit tests'
    inputs:
      target: Unit-Tests

- job: iOS
  pool:
    vmImage: 'macOS-10.13'
  variables:
    buildConfiguration: 'Release'
  steps:
  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: 4.5
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '**/*.sln'
  - task: XamariniOS@2
    displayName: 'Build iOS'
    inputs:
      solutionFile: '**/*.sln'
      configuration: '$(buildConfiguration)'
      buildForSimulator: true
      packageApp: false
  - script: 'curl -Lsfo build.sh https://cakebuild.net/download/bootstrapper/osx && chmod +x build.sh && ./build.sh -Target="Unit-Tests"'
    displayName: 'Run unit tests'